name: nasa_apod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  dio: ^5.1.2
  flutter_modular: ^5.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.1.1
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3

scripts:
  build: "flutter packages run build_runner build"
  watch: "flutter packages run build_runner watch"
  delete: "flutter packages run build_runner build --delete-conflicting-outputs"
  format: "flutter format --line-length 80 ./lib/core/ ./lib/modules/ ./lib/main.dart ./lib/app_module.dart ./lib/app_widget.dart ./lib/firebase_options.dart"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.2
  freezed: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
